version: '3'
services:
  db:
    image: postgres:latest
    restart: always
    ports:
      - '5433:5432'
    environment:
      POSTGRES_DB: mybook
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: 123456789
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
